-- 테이블에서 데이터를 검색:
-- (1) projection: 테이블에서 원하는 컬럼들을 선택.
-- (2) selection: 테이블에서 조건을 만족하는 레코드(행, row)들을 검색.
-- select column_name, ... 
-- from table_name 
-- where 조건식 
-- order by column_name, ...;
